site_name: Amano DB
theme:
  name: material

repo_name: kodemore/amano
repo_url: https://github.com/kodemore/amano

nav:
- Overview: index.md
- Item:
  - Defining Item: item/defining_item.md
  - Working with Item: item/working_with.md
  - Field mapping: item/field_mapping.md
  - Advanced features: item/advanced_features.md
- Table:
    - Basic Usage (CRUD): table/basic_usage.md
    - Querying a table: table/querying.md
    - Conditional writes: table/conditional_writes.md
    - Consistency model: table/consistency.md
    - Bulk operations: table/bulk.md
    - Working with schema: table/schema.md
- Testing: testing.md
- Cookbook: cookbook.md

markdown_extensions:
- pymdownx.highlight
- pymdownx.extra
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
