TYPE_STRING = 'S'
TYPE_NUMBER = 'N'
TYPE_BINARY = 'B'
TYPE_STRING_SET = 'SS'
TYPE_NUMBER_SET = 'NS'
TYPE_BINARY_SET = 'BS'
TYPE_NULL = 'NULL'
TYPE_BOOLEAN = 'BOOL'
TYPE_MAP = 'M'
TYPE_LIST = 'L'

ATTRIBUTE_TYPES = (
    TYPE_STRING,
    TYPE_NUMBER,
    TYPE_BINARY,
    TYPE_STRING_SET,
    TYPE_NUMBER_SET,
    TYPE_BINARY_SET,
    TYPE_NULL,
    TYPE_BOOLEAN,
    TYPE_MAP,
    TYPE_LIST,
)
